"use client";
import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import Providers from "./provider";

const inter = Hind_Siliguri({
  subsets: ["bengali"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-hind-siliguri",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   icons: [{ rel: "icon", url: Favicon.src }],
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>কচুয়া কিন্ডারগার্টেন এসোসিয়েশন</title>
        <meta name="description" content="কচুয়া কিন্ডারগার্টেন এসোসিয়েশন" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.svg" />
      </head>
      <body className={`bg-transparent ${inter.className} `}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
