"use client";
/* eslint-disable @next/next/no-img-element */
import { Button, Footer, Navbar } from "flowbite-react";
import {
  BsDribbble,
  BsFacebook,
  BsGithub,
  BsInstagram,
  BsTwitter,
} from "react-icons/bs";
import { HiOutlineArrowRight } from "react-icons/hi";

import { useSession } from "next-auth/react";

import Link from "next/link";
import { usePathname } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function Layout({ children }: { children: React.ReactNode }) {
  const { data: session, status } = useSession();
  const userName = session?.user?.name;
  const currentRoute = usePathname();
  return (
    <div className="font-hind bg-transparent ">
      <Navbar fluid rounded>
        <Navbar.Brand className="h-6 sm:h-9" href="/">
          <div className="h-6 w-10 sm:h-9 block ">
            <img
              alt="Logo"
              className="mr-3 h-6 min-w-6 block sm:h-9"
              src="../icon.svg"
              height={36}
              width={36}
            />
          </div>
          <span className="hidden lg:block ml-3 self-center whitespace-nowrap text-xl font-semibold dark:text-white">
            কচুয়া কিন্ডারগার্টেন এসোসিয়েশন
          </span>
        </Navbar.Brand>
        <div className="flex md:order-2">
          <Link
            className={`font-semibold ${
              currentRoute === "/result" && "hidden"
            }`}
            href="/result"
          >
            <Button className="bg-indigo-700 focus:ring-indigo-700 enabled:hover:bg-blue-800 mx-3 text-[18px] font-semibold dark:bg-indigo-600 dark:enabled:hover:bg-indigo-700 dark:focus:ring-indigo-800 lg:hidden">
              রেজাল্ট
            </Button>
          </Link>
          {status === "loading" ? (
            <div className="flex items-center justify-center px-2 py-2 lg:pl-12 mr-4">
              <svg
                className="animate-spin -ml-1 mr-3 h-6 w-6 text-indigo-700"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
              >
                <circle
                  className="opacity-25"
                  cx={12}
                  cy={12}
                  r={10}
                  stroke="currentColor"
                  strokeWidth={3}
                />
                <path
                  className="opacity-75"
                  fill="currentColor"
                  d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                />
              </svg>
            </div>
          ) : userName ? (
            <Link className="font-semibold" href="/dashboard">
              <Button className="bg-indigo-700 focus:ring-indigo-700 enabled:hover:bg-blue-800 mx-3 text-[18px] font-semibold dark:bg-indigo-600 dark:enabled:hover:bg-indigo-700 dark:focus:ring-indigo-800">
                ড্যাশবোর্ড
                <HiOutlineArrowRight className="ml-2 h-5 w-5" />
              </Button>
            </Link>
          ) : (
            <Link className="font-semibold" href="/login">
              <Button className="bg-indigo-700 focus:ring-indigo-700 enabled:hover:bg-blue-800 mx-3 text-[18px] font-semibold dark:bg-indigo-600 dark:enabled:hover:bg-indigo-700 dark:focus:ring-indigo-800">
                লগইন
                <HiOutlineArrowRight className="ml-2 h-5 w-5" />
              </Button>
            </Link>
          )}
          <Navbar.Toggle />
        </div>
        <Navbar.Collapse>
          <Link
            className={`block py-2 pr-4 pl-3 md:p-0 border-b border-gray-100  hover:bg-gray-50 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:border-0 md:hover:bg-transparent md:hover:text-indigo-700 md:dark:hover:bg-transparent md:dark:hover:text-white text-[18px] font-semibold ${
              currentRoute === "/" ? "md:text-indigo-700" : "text-gray-700"
            }`}
            href="/"
          >
            হোম
          </Link>

          <Link
            className={`block py-2 pr-4 pl-3 md:p-0 border-b border-gray-100  hover:bg-gray-50 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:border-0 md:hover:bg-transparent md:hover:text-indigo-700 md:dark:hover:bg-transparent md:dark:hover:text-white text-[18px] font-semibold ${
              currentRoute === "/gallery"
                ? "md:text-indigo-700"
                : "text-gray-700"
            }`}
            href="/gallery"
          >
            গ্যালারী
          </Link>
          <Link
            className={`block py-2 pr-4 pl-3 md:p-0 border-b border-gray-100  hover:bg-gray-50 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:border-0 md:hover:bg-transparent md:hover:text-indigo-700 md:dark:hover:bg-transparent md:dark:hover:text-white text-[18px] font-semibold ${
              currentRoute === "/notice"
                ? "md:text-indigo-700"
                : "text-gray-700"
            }`}
            href="/notice"
          >
            নোটিশ
          </Link>

          <Link
            className={`block py-2 pr-4 pl-3 md:p-0 border-b border-gray-100  hover:bg-gray-50 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:border-0 md:hover:bg-transparent md:hover:text-indigo-700 md:dark:hover:bg-transparent md:dark:hover:text-white text-[18px] font-semibold ${
              currentRoute === "/result"
                ? "md:text-indigo-700"
                : "text-gray-700"
            }`}
            href="/result"
          >
            রেজাল্ট
          </Link>

          <Link
            className={`block py-2 pr-4 pl-3 md:p-0 border-b border-gray-100 text-gray-700 hover:bg-gray-50 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:border-0 md:hover:bg-transparent md:hover:text-indigo-700 md:dark:hover:bg-transparent md:dark:hover:text-white text-[18px] font-semibold ${
              currentRoute === "/about" ? "md:text-indigo-700" : "text-gray-700"
            }`}
            href="/about"
          >
            আমাদের সম্পর্কে
          </Link>
        </Navbar.Collapse>
      </Navbar>
      <div className="bg-trasparent">{children}</div>
      <Footer container className="rounded-t-none	">
        <div className="w-full">
          <div className="grid w-full justify-between sm:flex sm:justify-between md:flex md:grid-cols-1">
            <div>
              <Footer.Brand
                alt="Logo"
                href="https://kkabd.org"
                name="KKA"
                src="../icon.svg"
                height={32}
                width={32}
              />
            </div>
            <div className="grid grid-cols-2 gap-8 sm:mt-4 sm:grid-cols-3 sm:gap-6">
              <div>
                <Footer.Title title="about" />
              </div>
              <div>
                <Footer.Title title="Follow us" />
              </div>
              <div>
                <Footer.Title title="Legal" />
              </div>
            </div>
          </div>
          <Footer.Divider className="lg:my-4 my-4" />
          <div className="w-full sm:flex sm:items-center sm:justify-between">
            <Footer.Copyright by="KKA™" href="#" year={2023} />
            <div className="mt-4 flex space-x-6 sm:mt-0 sm:justify-center">
              <Footer.Icon href="#" icon={BsFacebook} />
              <Footer.Icon href="#" icon={BsInstagram} />
              <Footer.Icon href="#" icon={BsTwitter} />
              <Footer.Icon href="#" icon={BsGithub} />
              <Footer.Icon href="#" icon={BsDribbble} />
            </div>
          </div>
        </div>
      </Footer>
    </div>
  );
}
